# Fix contacts page
path = "frontend/src/app/dashboard/contacts/page.tsx"
lines = []
def a(s): lines.append(s)


a("'use client'")
a("")
a("import { useState, useEffect } from 'react'")
a("import { contactsApi, api } from '@/lib/api'")
a("")
a("interface Contact {")
a("  contact_id: number")
a("  lead_id: number | null")
a("  client_name: string")
a("  first_name: string")
a("  last_name: string")
a("  title: string")
a("  email: string")
a("  phone: string")
a("  location_state: string")
a("  priority_level: string")
a("  validation_status: string")
a("  source: string")
a("}")
a("")
a("export default function ContactsPage() {")
a("  const [contacts, setContacts] = useState<Contact[]>([])")
a("  const [loading, setLoading] = useState(true)")
a("  const [error, setError] = useState('')")
a("  const [page, setPage] = useState(1)")
a("  const [total, setTotal] = useState(0)")
a("  const [pageSize, setPageSize] = useState(25)")
a("  const [search, setSearch] = useState('')")
a("  const [filterPriority, setFilterPriority] = useState('')")
a("  const [filterValidation, setFilterValidation] = useState('')")
a("  const [debouncedSearch, setDebouncedSearch] = useState('')")
a("")
a("  useEffect(() => {")
a("    const timer = setTimeout(() => setDebouncedSearch(search), 300)")
a("    return () => clearTimeout(timer)")
a("  }, [search])")
a("")
a("  useEffect(() => {")
a("    fetchContacts()")
a("  }, [page, pageSize, debouncedSearch, filterPriority, filterValidation])")
a("")

a("  const fetchContacts = async () => {")
a("    try {")
a("      setLoading(true)")
a("      const params: Record<string, any> = { page, page_size: pageSize }")
a("      if (debouncedSearch) params.search = debouncedSearch")
a("      if (filterPriority) params.priority_level = filterPriority")
a("      if (filterValidation) params.validation_status = filterValidation")
a("")
a("      const response = await contactsApi.list(params)")
a("      const contactList = Array.isArray(response) ? response : (response?.items || [])")
a("      setContacts(contactList)")
a("      setTotal(response?.total || contactList.length)")
a("    } catch (err: any) {")
a("      setError(err.response?.data?.detail || 'Failed to fetch contacts')")
a("    } finally {")
a("      setLoading(false)")
a("    }")
a("  }")
a("")
a("  const getValidationBadge = (status: string) => {")
a("    const colors: Record<string, string> = {")
a("      valid: 'bg-green-100 text-green-800',")
a("      invalid: 'bg-red-100 text-red-800',")
a("      unknown: 'bg-gray-100 text-gray-800',")
a("      pending: 'bg-yellow-100 text-yellow-800',")
a("    }")
a("    return colors[status] || 'bg-gray-100 text-gray-800'")
a("  }")
a("")
a("  const getPriorityBadge = (priority: string) => {")
a("    if (\!priority) return 'bg-gray-100 text-gray-800'")
a("    const level = priority.split('_')[0]")
a("    const colors: Record<string, string> = {")
a("      p1: 'bg-red-100 text-red-800',")
a("      p2: 'bg-orange-100 text-orange-800',")
a("      p3: 'bg-yellow-100 text-yellow-800',")
a("      p4: 'bg-blue-100 text-blue-800',")
a("      p5: 'bg-gray-100 text-gray-800',")
a("    }")
a("    return colors[level] || 'bg-gray-100 text-gray-800'")
a("  }")
a("")
a("  const getPriorityLabel = (priority: string) => {")
a("    if (\!priority) return '-'")
a("    const labels: Record<string, string> = {")
a("      p1_job_poster: 'P1 - Job Poster',")
a("      p2_hr_ta_recruiter: 'P2 - HR/Recruiter',")
a("      p3_hr_manager: 'P3 - HR Manager',")
a("      p4_ops_leader: 'P4 - Ops Leader',")
a("      p5_functional_manager: 'P5 - Func. Mgr',")
a("    }")
a("    return labels[priority] || priority.split('_')[0].toUpperCase()")
a("  }")
a("")
a("  const totalPages = Math.ceil(total / pageSize) || 1")
a("")
# JSX return
a("  return (")
a("    <div>")
a("      <div className="+"\"flex justify-between items-center mb-6\""+">")
a("        <div>")
a("          <h1 className="+"\"text-2xl font-bold text-gray-800\""+">Contacts</h1>")
a("          <p className="+"\"text-gray-500 text-sm mt-1\""+">")
a("            {total} contacts discovered from lead enrichment")
a("          </p>")
a("        </div>")
a("      </div>")
a("")
a("      {error && (")
a("        <div className="+"\"bg-red-50 text-red-600 px-4 py-2 rounded-lg mb-4 flex justify-between\""+">")
a("          <span>{error}</span>")
a("          <button onClick={() => setError('')} className="+"\"font-bold\""+">x</button>")
a("        </div>")
a("      )}")
a("")
a("      {/* Search and Filters */}")
a("      <div className="+"\"card p-4 mb-4\""+">")
a("        <div className="+"\"flex flex-wrap gap-4 items-center\""+">")
a("          <div className="+"\"flex-1 min-w-64\""+">")
a("            <input")
a("              type="+"\"text\""+"")
a("              placeholder="+"\"Search name, email, or company...\""+"")
a("              value={search}")
a("              onChange={(e) => { setSearch(e.target.value); setPage(1); }}")
a("              className="+"\"input w-full\""+"")
a("            />")
a("          </div>")
a("          <select")
a("            value={filterPriority}")
a("            onChange={(e) => { setFilterPriority(e.target.value); setPage(1); }}")
a("            className="+"\"input w-44\""+"")
a("          >")
a("            <option value="+"\"\""+">All Priorities</option>")
a("            <option value="+"\"p1_job_poster\""+">P1 - Job Poster</option>")
a("            <option value="+"\"p2_hr_ta_recruiter\""+">P2 - HR/Recruiter</option>")
a("            <option value="+"\"p3_hr_manager\""+">P3 - HR Manager</option>")
a("            <option value="+"\"p4_ops_leader\""+">P4 - Ops Leader</option>")
a("            <option value="+"\"p5_functional_manager\""+">P5 - Func. Mgr</option>")
a("          </select>")
a("          <select")
a("            value={filterValidation}")
a("            onChange={(e) => { setFilterValidation(e.target.value); setPage(1); }}")
a("            className="+"\"input w-40\""+"")
a("          >")
a("            <option value="+"\"\""+">All Validation</option>")
a("            <option value="+"\"valid\""+">Valid</option>")
a("            <option value="+"\"invalid\""+">Invalid</option>")
a("            <option value="+"\"pending\""+">Pending</option>")
a("            <option value="+"\"unknown\""+">Unknown</option>")
a("          </select>")
a("          <select")
a("            value={pageSize}")
a("            onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}")
a("            className="+"\"input w-36\""+"")
a("          >")
a("            <option value="+"\"10\""+">10 per page</option>")
a("            <option value="+"\"25\""+">25 per page</option>")
a("            <option value="+"\"50\""+">50 per page</option>")
a("            <option value="+"\"100\""+">100 per page</option>")
a("          </select>")
a("        </div>")
a("      </div>")
a("")
a("      <div className="+"\"card overflow-hidden\""+">")
a("        <div className="+"\"overflow-x-auto\""+">")
a("          <table className="+"\"min-w-full divide-y divide-gray-200\""+">")
a("            <thead className="+"\"bg-gray-50\""+">")
a("              <tr>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Name</th>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Company</th>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Email</th>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Priority</th>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Validation</th>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Lead ID</th>")
a("                <th className="+"\"px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\""+">Source</th>")
a("              </tr>")
a("            </thead>")
a("            <tbody className="+"\"bg-white divide-y divide-gray-200\""+">")
a("              {loading ? (")
a("                <tr><td colSpan={7} className="+"\"px-4 py-8 text-center text-gray-500\""+">Loading contacts...</td></tr>")
a("              ) : contacts.length === 0 ? (")
a("                <tr><td colSpan={7} className="+"\"px-4 py-8 text-center text-gray-500\""+">No contacts found. Run Contact Enrichment pipeline to discover contacts.</td></tr>")
a("              ) : (")
a("                contacts.map((contact) => (")
a("                  <tr key={contact.contact_id} className="+"\"hover:bg-gray-50\""+">")
a("                    <td className="+"\"px-4 py-3\""+">")
a("                      <div className="+"\"text-sm font-medium text-gray-900\""+">{contact.first_name} {contact.last_name}</div>")
a("                      <div className="+"\"text-sm text-gray-500\""+">{contact.title || '-'}</div>")
a("                    </td>")
a("                    <td className="+"\"px-4 py-3 text-sm text-gray-500\""+">{contact.client_name || '-'}</td>")
a("                    <td className="+"\"px-4 py-3 text-sm\""+">")
a("                      {contact.email ? (")
a("                        <a href={'mailto:' + contact.email} className="+"\"text-blue-600 hover:underline\""+">{contact.email}</a>")
a("                      ) : '-'}")
a("                    </td>")
a("                    <td className="+"\"px-4 py-3\""+">")
a("                      {contact.priority_level ? (")
a("                        <span className={'px-2 py-1 text-xs rounded-full ' + getPriorityBadge(contact.priority_level)}>")
a("                          {getPriorityLabel(contact.priority_level)}")
a("                        </span>")
a("                      ) : '-'}")
a("                    </td>")
a("                    <td className="+"\"px-4 py-3\""+">")
a("                      <span className={'px-2 py-1 text-xs rounded-full ' + getValidationBadge(contact.validation_status || 'unknown')}>")
a("                        {contact.validation_status || 'pending'}")
a("                      </span>")
a("                    </td>")
a("                    <td className="+"\"px-4 py-3 text-sm\""+">")
a("                      {contact.lead_id ? (")
a("                        <span className="+"\"text-xs px-2 py-1 rounded bg-purple-50 text-purple-700 font-mono\""+">#"+"{contact.lead_id}</span>")
a("                      ) : <span className="+"\"text-gray-400\""+">-</span>}")
a("                    </td>")
a("                    <td className="+"\"px-4 py-3 text-sm text-gray-500\""+">{contact.source || '-'}</td>")
a("                  </tr>")
a("                ))")
a("              )}")
a("            </tbody>")
a("          </table>")
a("        </div>")
a("")
a("        {/* Pagination */}")
a("        <div className="+"\"bg-gray-50 px-6 py-3 flex items-center justify-between border-t\""+">")
a("          <div className="+"\"text-sm text-gray-500\""+">")
a("            Showing {contacts.length > 0 ? ((page - 1) * pageSize) + 1 : 0} to {Math.min(page * pageSize, total)} of {total} contacts")
a("          </div>")
a("          <div className="+"\"flex gap-2 items-center\""+">")
a("            <button onClick={() => setPage(1)} disabled={page === 1} className="+"\"px-2 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100\""+">&laquo;</button>")
a("            <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="+"\"px-3 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100\""+">Previous</button>")
a("            <span className="+"\"px-3 py-1 text-sm text-gray-600\""+">Page {page} of {totalPages}</span>")
a("            <button onClick={() => setPage(p => p + 1)} disabled={page * pageSize >= total} className="+"\"px-3 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100\""+">Next</button>")
a("            <button onClick={() => setPage(totalPages)} disabled={page * pageSize >= total} className="+"\"px-2 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100\""+">&raquo;</button>")
a("          </div>")
a("        </div>")
a("      </div>")
a("    </div>")
a("  )")
a("}")

# Write the file
content = "\n".join(lines) + "\n"
with open(path, "w") as f:
    f.write(content)
print(f"Wrote {len(lines)} lines to {path}")
