# Generate validation page
output = "frontend/src/app/dashboard/validation/page.tsx"
L = []
def a(s): L.append(s)

a("'use client'")
a('')
a("import { useState, useEffect } from 'react'")
a("import { contactsApi, pipelinesApi, api } from '@/lib/api'")
a('')
a('interface Contact {')
a('  contact_id: number')
a('  lead_id: number | null')
a('  client_name: string')
a('  first_name: string')
a('  last_name: string')
a('  email: string')
a('  title: string')
a('  priority_level: string')
a('  validation_status: string')
a('  source: string')
a('}')
a('')
a('interface ValidationStats {')
a('  total: number')
a('  by_validation: Record<string, number>')
a('}')
a('')
a("type SortField = 'first_name' | 'client_name' | 'email' | 'validation_status' | 'source'")
a("type SortOrder = 'asc' | 'desc'")
a('')
a('export default function ValidationPage() {')
a('  const [contacts, setContacts] = useState<Contact[]>([])')
a('  const [stats, setStats] = useState<ValidationStats>({ total: 0, by_validation: {} })')
a('  const [loading, setLoading] = useState(true)')
a('  const [validating, setValidating] = useState(false)')
a("  const [error, setError] = useState('')")
a("  const [success, setSuccess] = useState('')")
a('  const [page, setPage] = useState(1)')
a('  const [total, setTotal] = useState(0)')
a('  const [pageSize, setPageSize] = useState(25)')
a('')
a('  // Search and filters')
a("  const [search, setSearch] = useState('')")
a("  const [debouncedSearch, setDebouncedSearch] = useState('')")
a("  const [filterValidation, setFilterValidation] = useState('')")
a("  const [filterSource, setFilterSource] = useState('')")
a('')
a('  // Sorting')
a("  const [sortBy, setSortBy] = useState<SortField>('email')")
a("  const [sortOrder, setSortOrder] = useState<SortOrder>('asc')")
a('')
a('  useEffect(() => {')
a('    const timer = setTimeout(() => setDebouncedSearch(search), 300)')
a('    return () => clearTimeout(timer)')
a('  }, [search])')
a('')
a('  useEffect(() => {')
a('    fetchContacts()')
a('  }, [page, pageSize, debouncedSearch, filterValidation, filterSource])')
a('')
a('  useEffect(() => {')
a('    fetchStats()')
a('  }, [])')
a('')
a('  const fetchStats = async () => {')
a('    try {')
a("      const response = await api.get('/contacts/stats')")
a('      setStats(response.data)')
a('    } catch (err) {')
a('      // Stats are non-critical')
a('    }')
a('  }')
a('')
a('  const fetchContacts = async () => {')
a('    try {')
a('      setLoading(true)')
a('      const params: Record<string, any> = { page, page_size: pageSize }')
a('      if (debouncedSearch) params.search = debouncedSearch')
a('      if (filterValidation) params.validation_status = filterValidation')
a('      if (filterSource) params.source = filterSource')
a('')
a('      const response = await contactsApi.list(params)')
a('      const contactList = Array.isArray(response) ? response : (response?.items || [])')
a('      setContacts(contactList)')
a('      setTotal(response?.total || contactList.length)')
a('    } catch (err: any) {')
a("      setError(err.response?.data?.detail || 'Failed to fetch contacts')")
a('    } finally {')
a('      setLoading(false)')
a('    }')
a('  }')
a('')
a('  const runValidation = async () => {')
a('    try {')
a('      setValidating(true)')
a("      setError('')")
a("      setSuccess('')")
a('      await pipelinesApi.runEmailValidation()')
a("      setSuccess('Email validation pipeline started! Check Pipelines page for progress.')")
a('      setTimeout(() => { fetchContacts(); fetchStats(); }, 2000)')
a('    } catch (err: any) {')
a("      setError(err.response?.data?.detail || 'Failed to start validation pipeline')")
a('    } finally {')
a('      setValidating(false)')
a('    }')
a('  }')
a('')
a('  const getStatusBadge = (status: string) => {')
a('    const colors: Record<string, string> = {')
a("      valid: 'bg-green-100 text-green-800',")
a("      invalid: 'bg-red-100 text-red-800',")
a("      pending: 'bg-yellow-100 text-yellow-800',")
a("      unknown: 'bg-gray-100 text-gray-800',")
a('    }')
a("    return colors[status] || 'bg-gray-100 text-gray-800'")
a('  }')
a('')
a('  // Client-side sorting')
a('  const sortedContacts = [...contacts].sort((a, b) => {')
a("    let aVal = (a[sortBy] || '').toString().toLowerCase()")
a("    let bVal = (b[sortBy] || '').toString().toLowerCase()")
a("    if (aVal < bVal) return sortOrder === 'asc' ? -1 : 1")
a("    if (aVal > bVal) return sortOrder === 'asc' ? 1 : -1")
a('    return 0')
a('  })')
a('')
a('  const handleSort = (field: SortField) => {')
a('    if (sortBy === field) {')
a("      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')")
a('    } else {')
a('      setSortBy(field)')
a("      setSortOrder('asc')")
a('    }')
a('  }')
a('')
a('  const SortIcon = ({ field }: { field: SortField }) => {')
a('    if (sortBy !== field) return <span className="text-gray-300 ml-1">&#8645;</span>')
a('    return sortOrder === \'asc\' ? <span className="ml-1">&#8593;</span> : <span className="ml-1">&#8595;</span>')
a('  }')
a('')
a('  const totalPages = Math.ceil(total / pageSize) || 1')
a('  const validCount = stats.by_validation?.valid || 0')
a('  const invalidCount = stats.by_validation?.invalid || 0')
a('  const pendingCount = stats.by_validation?.pending || 0')
a('  const unknownCount = stats.total - validCount - invalidCount - pendingCount')
a('  const activeFiltersCount = [filterValidation, filterSource, search].filter(Boolean).length')
a('')
a('  return (')
a('    <div>')
a('      <div className="flex justify-between items-center mb-6">')
a('        <div>')
a('          <h1 className="text-2xl font-bold text-gray-800">Email Validation</h1>')
a('          <p className="text-gray-500 mt-1">Validate contact emails before outreach</p>')
a('        </div>')
a('        <button')
a('          onClick={runValidation}')
a('          disabled={validating}')
a('          className="btn-primary"')
a('        >')
a("          {validating ? 'Starting...' : 'Run Validation Pipeline'}")
a('        </button>')
a('      </div>')
a('')
a('      {error && (')
a('        <div className="bg-red-50 text-red-600 px-4 py-2 rounded-lg mb-4 flex justify-between">')
a('          <span>{error}</span>')
a('          <button onClick={() => setError(\'\')} className="font-bold">x</button>')
a('        </div>')
a('      )}')
a('')
a('      {success && (')
a('        <div className="bg-green-50 text-green-600 px-4 py-2 rounded-lg mb-4">')
a('          {success}')
a('        </div>')
a('      )}')
a('')
a('      {/* Stats Cards */}')
a('      <div className="grid grid-cols-5 gap-4 mb-6">')
a('        <div className="card p-4 text-center cursor-pointer hover:shadow-md" onClick={() => { setFilterValidation(\'\'); setPage(1); }}>')
a('          <div className="text-2xl font-bold text-gray-800">{stats.total}</div>')
a('          <div className="text-sm text-gray-500">Total Contacts</div>')
a('        </div>')
a('        <div className="card p-4 text-center border-l-4 border-green-500 cursor-pointer hover:shadow-md" onClick={() => { setFilterValidation(\'valid\'); setPage(1); }}>')
a('          <div className="text-2xl font-bold text-green-600">{validCount}</div>')
a('          <div className="text-sm text-gray-500">Valid</div>')
a('        </div>')
a('        <div className="card p-4 text-center border-l-4 border-red-500 cursor-pointer hover:shadow-md" onClick={() => { setFilterValidation(\'invalid\'); setPage(1); }}>')
a('          <div className="text-2xl font-bold text-red-600">{invalidCount}</div>')
a('          <div className="text-sm text-gray-500">Invalid</div>')
a('        </div>')
a('        <div className="card p-4 text-center border-l-4 border-yellow-500 cursor-pointer hover:shadow-md" onClick={() => { setFilterValidation(\'pending\'); setPage(1); }}>')
a('          <div className="text-2xl font-bold text-yellow-600">{pendingCount}</div>')
a('          <div className="text-sm text-gray-500">Pending</div>')
a('        </div>')
a('        <div className="card p-4 text-center border-l-4 border-gray-400 cursor-pointer hover:shadow-md" onClick={() => { setFilterValidation(\'unknown\'); setPage(1); }}>')
a('          <div className="text-2xl font-bold text-gray-600">{unknownCount < 0 ? 0 : unknownCount}</div>')
a('          <div className="text-sm text-gray-500">Not Validated</div>')
a('        </div>')
a('      </div>')
a('')
a('      {/* Workflow Info */}')
a('      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">')
a('        <h3 className="font-semibold text-blue-800 mb-2">Validation Workflow</h3>')
a('        <div className="flex items-center text-sm text-blue-700">')
a('          <span className="px-2 py-1 bg-blue-100 rounded">1. Leads Sourced</span>')
a('          <span className="mx-2">&rarr;</span>')
a('          <span className="px-2 py-1 bg-blue-100 rounded">2. Contacts Enriched</span>')
a('          <span className="mx-2">&rarr;</span>')
a('          <span className="px-2 py-1 bg-blue-200 rounded font-semibold">3. Emails Validated</span>')
a('          <span className="mx-2">&rarr;</span>')
a('          <span className="px-2 py-1 bg-blue-100 rounded">4. Outreach Sent</span>')
a('        </div>')
a('      </div>')
a('')
a('      {/* Search and Filters */}')
a('      <div className="card p-4 mb-4">')
a('        <div className="flex flex-wrap gap-4 items-center">')
a('          <div className="flex-1 min-w-64">')
a('            <input')
a('              type="text"')
a('              placeholder="Search name, email, or company..."')
a('              value={search}')
a('              onChange={(e) => { setSearch(e.target.value); setPage(1); }}')
a('              className="input w-full"')
a('            />')
a('          </div>')
a('          <select')
a('            value={filterValidation}')
a('            onChange={(e) => { setFilterValidation(e.target.value); setPage(1); }}')
a('            className="input w-44"')
a('          >')
a('            <option value="">All Statuses</option>')
a('            <option value="valid">Valid</option>')
a('            <option value="invalid">Invalid</option>')
a('            <option value="pending">Pending</option>')
a('            <option value="unknown">Unknown</option>')
a('          </select>')
a('          <select')
a('            value={filterSource}')
a('            onChange={(e) => { setFilterSource(e.target.value); setPage(1); }}')
a('            className="input w-36"')
a('          >')
a('            <option value="">All Sources</option>')
a('            <option value="mock">Mock</option>')
a('            <option value="apollo">Apollo</option>')
a('            <option value="seamless">Seamless</option>')
a('          </select>')
a('          <select')
a('            value={pageSize}')
a('            onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}')
a('            className="input w-36"')
a('          >')
a('            <option value="10">10 per page</option>')
a('            <option value="25">25 per page</option>')
a('            <option value="50">50 per page</option>')
a('            <option value="100">100 per page</option>')
a('          </select>')
a('          {activeFiltersCount > 0 && (')
a('            <button')
a("              onClick={() => { setSearch(''); setFilterValidation(''); setFilterSource(''); setPage(1); }}")
a('              className="text-sm text-gray-500 hover:text-gray-700"')
a('            >')
a('              Clear all')
a('            </button>')
a('          )}')
a('        </div>')
a('      </div>')
a('')
a('      {/* Contacts Table */}')
a('      <div className="card overflow-hidden">')
a('        <div className="overflow-x-auto">')
a('          <table className="min-w-full divide-y divide-gray-200">')
a('            <thead className="bg-gray-50">')
a('              <tr>')
a('                <th')
a("                  onClick={() => handleSort('first_name')}")
a('                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100"')
a('                >')
a('                  Contact <SortIcon field={"first_name"} />')
a('                </th>')
a('                <th')
a("                  onClick={() => handleSort('client_name')}")
a('                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100"')
a('                >')
a('                  Company <SortIcon field={"client_name"} />')
a('                </th>')
a('                <th')
a("                  onClick={() => handleSort('email')}")
a('                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100"')
a('                >')
a('                  Email <SortIcon field={"email"} />')
a('                </th>')
a('                <th')
a("                  onClick={() => handleSort('validation_status')}")
a('                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100"')
a('                >')
a('                  Validation Status <SortIcon field={"validation_status"} />')
a('                </th>')
a('                <th')
a("                  onClick={() => handleSort('source')}")
a('                  className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100"')
a('                >')
a('                  Source <SortIcon field={"source"} />')
a('                </th>')
a('              </tr>')
a('            </thead>')
a('            <tbody className="bg-white divide-y divide-gray-200">')
a('              {loading ? (')
a('                <tr>')
a('                  <td colSpan={5} className="px-4 py-8 text-center text-gray-500">')
a('                    Loading validation data...')
a('                  </td>')
a('                </tr>')
a('              ) : sortedContacts.length === 0 ? (')
a('                <tr>')
a('                  <td colSpan={5} className="px-4 py-8 text-center text-gray-500">')
a("                    No contacts found. {activeFiltersCount > 0 ? 'Try adjusting your filters.' : 'Run Contact Enrichment pipeline first.'}")
a('                  </td>')
a('                </tr>')
a('              ) : (')
a('                sortedContacts.map((contact) => (')
a('                  <tr key={contact.contact_id} className="hover:bg-gray-50">')
a('                    <td className="px-4 py-3">')
a('                      <div className="text-sm font-medium text-gray-900">')
a('                        {contact.first_name} {contact.last_name}')
a('                      </div>')
a('                      <div className="text-sm text-gray-500">{contact.title || \'-\'}</div>')
a('                    </td>')
a('                    <td className="px-4 py-3 text-sm text-gray-500">')
a("                      {contact.client_name || '-'}")
a('                    </td>')
a('                    <td className="px-4 py-3 text-sm font-mono">')
a('                      {contact.email ? (')
a('                        <a href={\'mailto:\' + contact.email} className="text-blue-600 hover:underline">{contact.email}</a>')
a("                      ) : '-'}")
a('                    </td>')
a('                    <td className="px-4 py-3">')
a("                      <span className={'px-2 py-1 text-xs rounded-full ' + getStatusBadge(contact.validation_status || 'unknown')}>")
a("                        {contact.validation_status || 'not validated'}")
a('                      </span>')
a('                    </td>')
a('                    <td className="px-4 py-3 text-sm text-gray-500">')
a("                      {contact.source || '-'}")
a('                    </td>')
a('                  </tr>')
a('                ))')
a('              )}')
a('            </tbody>')
a('          </table>')
a('        </div>')
a('')
a('        {/* Pagination */}')
a('        <div className="bg-gray-50 px-6 py-3 flex items-center justify-between border-t">')
a('          <div className="text-sm text-gray-500">')
a('            Showing {contacts.length > 0 ? ((page - 1) * pageSize) + 1 : 0} to {Math.min(page * pageSize, total)} of {total} contacts')
a('          </div>')
a('          <div className="flex gap-2 items-center">')
a('            <button onClick={() => setPage(1)} disabled={page === 1} className="px-2 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100">&laquo;</button>')
a('            <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="px-3 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100">Previous</button>')
a('            <span className="px-3 py-1 text-sm text-gray-600">Page {page} of {totalPages}</span>')
a('            <button onClick={() => setPage(p => p + 1)} disabled={page * pageSize >= total} className="px-3 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100">Next</button>')
a('            <button onClick={() => setPage(totalPages)} disabled={page * pageSize >= total} className="px-2 py-1 border rounded text-sm disabled:opacity-50 hover:bg-gray-100">&raquo;</button>')
a('          </div>')
a('        </div>')
a('      </div>')
a('    </div>')
a('  )')
a('}')

# Write the file
content = chr(10).join(L) + chr(10)
with open(output, "w") as f:
    f.write(content)
print(f"Wrote {len(L)} lines to {output}")
