import os

filepath = os.path.join(
    r"C:\Ali\Rizwan-Taiyab\Exzelon\AI-Agent-RA\RA-01182026",
    "frontend", "src", "app", "dashboard", "settings", "page.tsx"
)

with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

old_start = "          {/* Exclusion Keywords Card */}"
old_end = chr(10) + "          <div className=" + chr(34) + "flex justify-end" + chr(34) + ">"

start_idx = content.index(old_start)
end_idx = content.index(old_end, start_idx)

q = chr(34)
s = chr(39)
bt = chr(96)
nl = chr(10)
dl = chr(36)
mul = chr(215)

def gen_cat(name, key, default_const, new_kw, set_new_kw):
    L = []
    L.append(f"              " + "{/* " + name + " */}")
    L.append(f"              <div>")
    L.append(f"                <div className={q}flex items-center justify-between mb-2{q}>")
    L.append(f"                  <label className={q}label mb-0{q}>")
    L.append(f"                    <span>{name}</span>")
    L.append(f"                    <span className={q}text-xs text-gray-500 ml-2{q}>")
    L.append("                      (" + "{" + f"jobSourceConfig.{key}.length" + "}" + " active)")
    L.append(f"                    </span>")
    L.append(f"                  </label>")
    L.append(f"                  <div className={q}flex gap-2{q}>")
    L.append("                    <button")
    L.append("                      onClick={" + "{" + "() => {")
    L.append(f"                        if (jobSourceConfig.{key}.length === 0) " + "{")
    L.append(f"                          setJobSourceConfig(" + "{" + f" ...jobSourceConfig, {key}: {default_const} " + "}" + ")")
    L.append("                        }" + " else " + "{")
    L.append(f"                          setJobSourceConfig(" + "{" + f" ...jobSourceConfig, {key}: [] " + "}" + ")")
    L.append("                        }")
    L.append("                      }}")
    L.append(f"                      className={q}text-xs text-blue-600 hover:text-blue-800 underline{q}")
    L.append("                    >")
    L.append("                      " + "{" + f"jobSourceConfig.{key}.length === 0 ? {s}Check All{s} : {s}Uncheck All{s}" + "}")
    L.append("                    </button>")
    L.append("                    <button")
    L.append(f"                      onClick=" + "{" + f"() => setJobSourceConfig(" + "{" + f" ...jobSourceConfig, {key}: [...{default_const}] " + "}" + ")" + "}")
    L.append(f"                      className={q}text-xs text-gray-500 hover:text-gray-700 underline{q}")
    L.append("                    >")
    L.append("                      Reset Defaults")
    L.append("                    </button>")
    L.append("                  </div>")
    L.append("                </div>")
    return L

def gen_chips(key, default_const):
    L = []
    L.append(f"                <div className={q}border border-gray-200 rounded-lg p-3 max-h-48 overflow-y-auto bg-white{q}>")
    L.append(f"                  <div className={q}flex flex-wrap gap-2{q}>")
    L.append("                    " + "{" + f"[...new Set([...jobSourceConfig.{key}, ...{default_const}])].sort().map((keyword) => " + "{")
    L.append(f"                      const isActive = jobSourceConfig.{key}.includes(keyword)")
    L.append(f"                      const isDefault = {default_const}.includes(keyword)")
    L.append("                      return (")
    L.append("                        <div")
    L.append("                          key=" + "{keyword}")
    L.append("                          className=" + "{" + bt + "inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs cursor-pointer transition-all " + dl + "{")
    L.append("                            isActive")
    L.append(f"                              ? {s}bg-red-100 text-red-800 border border-red-300{s}")
    L.append(f"                              : {s}bg-gray-100 text-gray-400 border border-gray-200 line-through{s}")
    L.append("                          }" + bt + "}")
    L.append("                          onClick={" + "() => {")
    L.append("                            if (isActive) {")
    L.append("                              setJobSourceConfig({")
    L.append("                                ...jobSourceConfig,")
    L.append(f"                                {key}: jobSourceConfig.{key}.filter(k => k !== keyword)")
    L.append("                              })")
    L.append("                            } else {")
    L.append("                              setJobSourceConfig({")
    L.append("                                ...jobSourceConfig,")
    L.append(f"                                {key}: [...jobSourceConfig.{key}, keyword]")
    L.append("                              })")
    L.append("                            }")
    L.append("                          }}")
    L.append("                        >")
    L.append(f"                          <input")
    L.append(f"                            type={q}checkbox{q}")
    L.append("                            checked={isActive}")
    L.append("                            onChange={() => {}}")
    L.append(f"                            className={q}w-3 h-3 cursor-pointer{q}")
    L.append("                          />")
    L.append("                          <span>" + "{keyword}" + "</span>")
    L.append("                          {!isDefault && (")
    L.append("                            <button")
    L.append("                              onClick={(e) => {")
    L.append("                                e.stopPropagation()")
    L.append("                                setJobSourceConfig({")
    L.append("                                  ...jobSourceConfig,")
    L.append(f"                                  {key}: jobSourceConfig.{key}.filter(k => k !== keyword)")
    L.append("                                })")
    L.append("                              }}")
    L.append(f"                              className={q}ml-1 text-red-500 hover:text-red-700 font-bold{q}")
    L.append(f"                              title={q}Remove custom keyword{q}")
    L.append("                            >")
    L.append("                              " + mul)
    L.append("                            </button>")
    L.append("                          )}")
    L.append("                        </div>")
    L.append("                      )")
    L.append("                    })}")
    L.append("                  </div>")
    L.append("                </div>")
    return L

def gen_input(key, new_kw, set_new_kw):
    L = []
    L.append(f"                <div className={q}flex gap-2 mt-2{q}>")
    L.append("                  <input")
    L.append(f"                    type={q}text{q}")
    L.append("                    value={" + new_kw + "}")
    L.append("                    onChange={(e) => " + set_new_kw + "(e.target.value)}")
    L.append("                    onKeyDown={(e) => {")
    L.append(f"                      if (e.key === {s}Enter{s} && {new_kw}.trim()) " + "{")
    L.append(f"                        const kw = {new_kw}.trim().toLowerCase()")
    L.append(f"                        if (!jobSourceConfig.{key}.includes(kw)) " + "{")
    L.append("                          setJobSourceConfig({")
    L.append("                            ...jobSourceConfig,")
    L.append(f"                            {key}: [...jobSourceConfig.{key}, kw]")
    L.append("                          })")
    L.append("                        }")
    L.append(f"                        {set_new_kw}({s}{s})")
    L.append("                      }")
    L.append("                    }}")
    L.append(f"                    placeholder={q}Add custom keyword...{q}")
    L.append(f"                    className={q}input text-xs flex-1{q}")
    L.append("                  />")
    L.append("                  <button")
    L.append("                    onClick={() => {")
    L.append(f"                      const kw = {new_kw}.trim().toLowerCase()")
    L.append(f"                      if (kw && !jobSourceConfig.{key}.includes(kw)) " + "{")
    L.append("                        setJobSourceConfig({")
    L.append("                          ...jobSourceConfig,")
    L.append(f"                          {key}: [...jobSourceConfig.{key}, kw]")
    L.append("                        })")
    L.append("                      }")
    L.append(f"                      {set_new_kw}({s}{s})")
    L.append("                    }}")
    L.append(f"                    className={q}btn-secondary text-xs px-3{q}")
    L.append("                  >")
    L.append("                    Add")
    L.append("                  </button>")
    L.append("                </div>")
    L.append(f"                <p className={q}text-xs text-gray-400 mt-1{q}>Checked = excluded from results. Uncheck to allow.</p>")
    L.append("              </div>")
    return L

# Assemble the complete card
all_lines = []
all_lines.append("          {/* Exclusion Keywords Card */}")
all_lines.append(f"          <div className={q}card p-6{q}>")
all_lines.append(f"            <h3 className={q}text-lg font-semibold text-gray-800 mb-2 flex items-center{q}>")
all_lines.append(f"              <span className={q}w-3 h-3 bg-red-500 rounded-full mr-2{q}></span>")
all_lines.append("              Exclusion Keywords")
all_lines.append("            </h3>")
all_lines.append(f"            <p className={q}text-sm text-gray-500 mb-4{q}>")
all_lines.append("              Jobs or companies containing <strong>checked</strong> keywords will be automatically excluded from lead sourcing.")
all_lines.append("              Uncheck a keyword to allow it. Add custom keywords or remove non-default ones.")
all_lines.append("            </p>")
all_lines.append("")
all_lines.append("            {/* Impact Info */}")
all_lines.append(f"            <div className={q}mb-4 p-3 bg-amber-50 border border-amber-200 rounded-lg{q}>")
all_lines.append(f"              <p className={q}text-xs text-amber-800{q}>")
all_lines.append("                <strong>IMPACT:</strong> Each checked keyword filters out ANY job/company containing it.")
all_lines.append("                Fewer checked keywords = more leads. Refined from broad terms to specific")
all_lines.append("                phrases to avoid false exclusions of legitimate non-IT roles.")
all_lines.append("              </p>")
all_lines.append("            </div>")
all_lines.append("")
all_lines.append(f"            <div className={q}grid grid-cols-2 gap-6{q}>")

# IT/Tech section
all_lines.extend(gen_cat("IT/Tech Role Keywords", "exclude_it_keywords", "DEFAULT_IT_EXCLUSIONS", "newITKeyword", "setNewITKeyword"))
all_lines.extend(gen_chips("exclude_it_keywords", "DEFAULT_IT_EXCLUSIONS"))
all_lines.extend(gen_input("exclude_it_keywords", "newITKeyword", "setNewITKeyword"))
all_lines.append("")

# Staffing section
all_lines.extend(gen_cat("Staffing/Agency Keywords", "exclude_staffing_keywords", "DEFAULT_STAFFING_EXCLUSIONS", "newStaffingKeyword", "setNewStaffingKeyword"))
all_lines.extend(gen_chips("exclude_staffing_keywords", "DEFAULT_STAFFING_EXCLUSIONS"))
all_lines.extend(gen_input("exclude_staffing_keywords", "newStaffingKeyword", "setNewStaffingKeyword"))

all_lines.append("            </div>")
all_lines.append("          </div>")
all_lines.append("")

new_section = nl.join(all_lines)

content_new = content[:start_idx] + new_section + content[end_idx:]

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content_new)

print(f"SUCCESS: Replaced exclusion keywords card")
print(f"New section: {len(all_lines)} lines, {len(new_section)} chars")
print(f"File size: {len(content)} -> {len(content_new)} bytes")
