lines = []
def a(s): lines.append(s)

a("'use client'")
a('')
a("import { useState, useEffect } from 'react'")
a("import { contactsApi, pipelinesApi, api } from '@/lib/api'")
a('')
a('interface Contact {')
a('  contact_id: number')
a('  lead_id: number | null')
a('  client_name: string')
a('  first_name: string')
a('  last_name: string')
a('  email: string')
a('  title: string')
a('  priority_level: string')
a('  validation_status: string')
a('  source: string')
a('}')
a('')
a('interface ValidationStats {')
a('  total: number')
a('  by_validation: Record<string, number>')
a('}')
a('')
a("type SortField = 'first_name' | 'client_name' | 'email' | 'validation_status' | 'source'")
a("type SortOrder = 'asc' | 'desc'")
a('')
a('export default function ValidationPage() {')
a('  const [contacts, setContacts] = useState<Contact[]>([])')
a('  const [stats, setStats] = useState<ValidationStats>({ total: 0, by_validation: {} })')
a('  const [loading, setLoading] = useState(true)')
a('  const [validating, setValidating] = useState(false)')
a("  const [error, setError] = useState('')")
a("  const [success, setSuccess] = useState('')")
a('  const [page, setPage] = useState(1)')
a('  const [total, setTotal] = useState(0)')
a('  const [pageSize, setPageSize] = useState(25)')
a('')
a('  // Search and filters')
a("  const [search, setSearch] = useState('')")
a("  const [debouncedSearch, setDebouncedSearch] = useState('')")
a("  const [filterValidation, setFilterValidation] = useState('')")
a("  const [filterSource, setFilterSource] = useState('')")
a('')
a('  // Sorting')
a("  const [sortBy, setSortBy] = useState<SortField>('email')")
a("  const [sortOrder, setSortOrder] = useState<SortOrder>('asc')")
a('')

with open("scripts/vp_lines.txt", "w") as f:
    f.write("
".join(lines))
